.PHONY: all self-test install uninstall

all: self-test

self-test:
	chmod +x ./self-test.sh
	./self-test.sh

install:
	chmod +x ./install.sh
	./install.sh

uninstall:
	chmod +x ./uninstall.sh
	./uninstall.sh
